### ISSUE TITLE
Fixed requests.exceptions.InvalidURL: Invalid URL : No host supplied

### ISSUE THREAD

**Issue by securiteinfo** [bambish/ScanQLi#1]
Hello,

When using recursive option (-r), I got some exceptions :

  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL u'https://#ecran-10': No host supplied

  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL u'https://#footer': No host supplied

Such URLs should just be ignored, it should not crash your software.

Example : 
python scanqli.py -u 'https://github.com' -r
   ____                   ____    __    _
  / __/ ____ ___ _  ___  / __ \  / /   (_)
 _\ \  / __// _ `/ / _ \/ /_/ / / /__ / /
/___/  \__/ \_,_/ /_//_/\___\_\/____//_/

https://github.com/bambish
https://twitter.com/bambishee

Base URL = https://github.com
Traceback (most recent call last):
  File "scanqli.py", line 118, in <module>
    pageset = function.GetAllPages(baseurl)
  File "/root/ScanQLi/function.py", line 176, in GetAllPages
    html = GetHTML(link)
  File "/root/ScanQLi/function.py", line 79, in GetHTML
    r = requests.get(url, cookies=cookies)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL u'https://#start-of-content': No host supplied

**Comment by bambish** [comment]
Hello,

Thanks for your report.
Have you got the same error with this: `python scanqli.py -u 'https://github.com/' -r` (with **/** at the end of the URL)?
If yes, could you give me your python version.
If no, I know where is the problem and I'm going to solve it :)

**EDIT:** Fixed

**Comment by securiteinfo** [comment]
cat /etc/debian_version
9.9
python -V
Python 2.7.13

**Comment by securiteinfo** [comment]
When your tool parses HTML to look for URLs, it may find this :
```

<div class="header-search">
                    <a id="tosearch" href="#search_container"<button id="header_search" type="button" class="btn small-btn btn-orange">Search</button></a>
                </div>
```

Then, your tool try to reach the found URL "https://#search_container". It is the cause of the crash.

**Comment by bambish** [comment]
My last commit normally fix this issue.

**Comment by securiteinfo** [comment]
Thank you !
